[package]
name = "common"
description = "common types, traits, and helper functions for Pelikan servers"
authors = ["Brian Martin <bmartin@twitter.com>"]

version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
boring = { workspace = true }
clocksource = { workspace = true }
macros = { path = "../macros" }
metriken = { workspace = true }
net = { path = "../net" }
rustcommon-logger = { workspace = true }
serde = { workspace = true, features = ["derive"] }
